name: format
on: [ push ]

permissions:
  contents: read

jobs:
  check-code-formatting:
    name: Code Formatting
    runs-on: ubuntu-24.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Print clang-format info
      run: |
        clang-format --version
